services:
  opa:
    image: openpolicyagent/opa:latest
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--addr=0.0.0.0:8181"
    ports:
      - "8181:8181"

  rasa:
    image: rasa/rasa:latest
    command: ["run", "--model", "RGO1.gz", "--enable-api", "--cors", "*"]
    ports:
      - "5005:5005"
    volumes:
      - "./rasa:/app"

  action-server:
    image: rasa/rasa-sdk:latest
    ports:
      - "5055:5055"
    volumes:
      - "./rasa/actions:/app/actions"
      - "./rasa/endpoints.yml:/app/endpoints.yml"
    depends_on:
      - rasa